# Generated by Django 5.2.1 on 2025-05-19 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('passport', models.CharField(max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
                ('warranty_years', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duties', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('production_year', models.IntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=3)),
                ('power', models.IntegerField()),
                ('transmission', models.CharField(choices=[('АКПП', 'Автомат'), ('МКПП', 'Механика')], max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_sold', models.BooleanField(default=False)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.bodytype')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Оформлен', 'Оформлен'), ('В процессе', 'В процессе'), ('Завершён', 'Завершён'), ('Отменён', 'Отменён')], default='Оформлен', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('prepayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Наличные', 'Наличные'), ('Карта', 'Карта'), ('Кредит', 'Кредит'), ('Перевод', 'Перевод')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.order')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('passport', models.CharField(max_length=20)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.position')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.staff'),
        ),
        migrations.AddField(
            model_name='car',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.staff'),
        ),
    ]
